### ISSUE TITLE
Not work with MacOS Big Sur

### ISSUE THREAD

**Issue by garudaonekh** [LilyGO/LILYGO-T-OI#11]
I install the driver from this git. but still can't detect the USB on my MacOS big sur.

Please help

**Comment by matphillips** [comment]
Would be nice if this were addressed.

**Comment by robertlipe** [comment]
See the related thread at https://github.com/LilyGO/LILYGO-T-OI/issues/3 where some people report success and some don't but at least the chip maker is there.

(I don't have this board and have never seen one, so please no PM to me. I was just researching related boards.)

**Comment by garudaonekh** [comment]
LiLyGO already release a new board which use ESp32-c3 instead(it's called T-IO Plus). It works with MacOS perfectly
